using System.Globalization;
using System.Text;
using AwgEasy.Contracts;

namespace AwgEasy.Node;

/// <summary>Renders the AmneziaWG interface config for this node from a desired-state bundle.</summary>
public static class ServerConfigRenderer
{
    public static string Render(DesiredStateBundle bundle, string egressInterface)
    {
        var network = Ipv4Network.Parse(bundle.Network.Subnet);
        var builder = new StringBuilder();

        builder.AppendLine("# Generated by awg-node. Do not edit by hand: it is overwritten on every sync.");
        builder.Append("# revision=").Append(bundle.Revision.ToString(CultureInfo.InvariantCulture))
            .Append(" identity-generation=").Append(bundle.Identity.Generation.ToString(CultureInfo.InvariantCulture))
            .Append(" issued=").AppendLine(bundle.IssuedAt.ToString("O", CultureInfo.InvariantCulture));

        builder.AppendLine("[Interface]");
        builder.Append("PrivateKey = ").AppendLine(bundle.Identity.ServerPrivateKey);
        builder.Append("Address = ").Append(network.GatewayAddress).Append('/')
            .AppendLine(network.PrefixLength.ToString(CultureInfo.InvariantCulture));
        builder.Append("ListenPort = ").AppendLine(bundle.Network.ListenPort.ToString(CultureInfo.InvariantCulture));

        if (bundle.Node.Mtu is { } mtu)
        {
            builder.Append("MTU = ").AppendLine(mtu.ToString(CultureInfo.InvariantCulture));
        }

        AppendObfuscation(builder, bundle.Obfuscation);

        builder.Append("PostUp = ").AppendLine(NatRule("-A", "-A", egressInterface));
        builder.Append("PostDown = ").AppendLine(NatRule("-D", "-D", egressInterface));

        foreach (var peer in bundle.Peers)
        {
            builder.AppendLine();
            builder.AppendLine("[Peer]");
            builder.Append("PublicKey = ").AppendLine(peer.PublicKey);
            if (!string.IsNullOrWhiteSpace(peer.PresharedKey))
            {
                builder.Append("PresharedKey = ").AppendLine(peer.PresharedKey);
            }

            builder.Append("AllowedIPs = ").Append(peer.Address).AppendLine("/32");
        }

        return builder.ToString();
    }

    private static string NatRule(string forwardOp, string natOp, string egressInterface)
        => $"iptables {forwardOp} FORWARD -i %i -j ACCEPT; iptables -t nat {natOp} POSTROUTING -o {egressInterface} -j MASQUERADE";

    /// <summary>
    /// Only the interface-side obfuscation (S1-S4, H1-H4) belongs in the node config. Jc/Jmin/Jmax
    /// and I1-I5 are client-side knobs and are rendered by the control plane into client configs.
    /// </summary>
    private static void AppendObfuscation(StringBuilder builder, ServerObfuscationProfile? obfuscation)
    {
        if (obfuscation is null)
        {
            return;
        }

        Append(builder, "S1", obfuscation.S1);
        Append(builder, "S2", obfuscation.S2);
        Append(builder, "S3", obfuscation.S3);
        Append(builder, "S4", obfuscation.S4);
        Append(builder, "H1", obfuscation.H1);
        Append(builder, "H2", obfuscation.H2);
        Append(builder, "H3", obfuscation.H3);
        Append(builder, "H4", obfuscation.H4);
    }

    private static void Append(StringBuilder builder, string key, int? value)
    {
        if (value.HasValue)
        {
            builder.Append(key).Append(" = ").AppendLine(value.Value.ToString(CultureInfo.InvariantCulture));
        }
    }

    private static void Append(StringBuilder builder, string key, string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
        {
            builder.Append(key).Append(" = ").AppendLine(value);
        }
    }
}
