using System.Globalization;
using System.Text;
using AwgEasy.Contracts;

namespace AwgEasy.Node;

/// <summary>Renders the AmneziaWG interface config for this node from a desired-state bundle.</summary>
public static class ServerConfigRenderer
{
    public static string Render(DesiredStateBundle bundle, string egressInterface)
    {
        var network = Ipv4Network.Parse(bundle.Network.Subnet);
        var builder = new StringBuilder();

        AppendProvenance(builder, bundle);

        builder.AppendLine("[Interface]");
        builder.AppendSetting("PrivateKey", bundle.Identity.ServerPrivateKey);
        builder.AppendSetting("Address", $"{network.GatewayAddress}/{network.PrefixLength.ToString(CultureInfo.InvariantCulture)}");
        builder.AppendSetting("ListenPort", bundle.Network.ListenPort);
        builder.AppendSetting("MTU", bundle.Node.Mtu);

        // Only the interface side. Jc/Jmin/Jmax and I1-I5 are client knobs and never belong here.
        builder.AppendInterfaceObfuscation(bundle.Obfuscation);

        builder.AppendSetting("PostUp", NatRule("-A", egressInterface));
        builder.AppendSetting("PostDown", NatRule("-D", egressInterface));

        foreach (var peer in bundle.Peers)
        {
            builder.AppendLine();
            builder.AppendLine("[Peer]");
            builder.AppendSetting("PublicKey", peer.PublicKey);
            builder.AppendSetting("PresharedKey", peer.PresharedKey);
            builder.AppendSetting("AllowedIPs", $"{peer.Address}/32");
        }

        return builder.ToString();
    }

    /// <summary>
    /// Stamps which revision produced this file. When a node misbehaves, the first question is
    /// always whether it is running what the control plane thinks it is.
    /// </summary>
    private static void AppendProvenance(StringBuilder builder, DesiredStateBundle bundle)
    {
        builder.AppendLine("# Generated by awg-node. Do not edit by hand: it is overwritten on every sync.");
        builder.Append("# revision=").Append(bundle.Revision.ToString(CultureInfo.InvariantCulture))
            .Append(" identity-generation=").Append(bundle.Identity.Generation.ToString(CultureInfo.InvariantCulture))
            .Append(" issued=").AppendLine(bundle.IssuedAt.ToString("O", CultureInfo.InvariantCulture));
    }

    private static string NatRule(string op, string egressInterface)
        => $"iptables {op} FORWARD -i %i -j ACCEPT; iptables -t nat {op} POSTROUTING -o {egressInterface} -j MASQUERADE";
}
