using System.Text.Json;
using System.Text.Json.Serialization;
using AwgEasy.Contracts;

namespace AwgEasy.Control;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(ClientResponse))]
[JsonSerializable(typeof(ClientResponse[]))]
[JsonSerializable(typeof(CreateClientRequest))]
[JsonSerializable(typeof(UpdateClientRequest))]
[JsonSerializable(typeof(ClientGroupResponse))]
[JsonSerializable(typeof(ClientGroupResponse[]))]
[JsonSerializable(typeof(CreateClientGroupRequest))]
[JsonSerializable(typeof(UpdateClientGroupRequest))]
[JsonSerializable(typeof(ReorderClientGroupsRequest))]
[JsonSerializable(typeof(ArrangeClientsRequest))]
[JsonSerializable(typeof(FleetResponse))]
[JsonSerializable(typeof(UpdateTunnelMtuRequest))]
[JsonSerializable(typeof(NodeResponse))]
[JsonSerializable(typeof(NodeResponse[]))]
[JsonSerializable(typeof(CreateNodeRequest))]
[JsonSerializable(typeof(DnsStatusResponse))]
[JsonSerializable(typeof(CloudflareRecordRequest))]
[JsonSerializable(typeof(CloudflareListResponse))]
[JsonSerializable(typeof(CloudflareRecordResponse))]
[JsonSerializable(typeof(CloudflareZoneResponse))]
[JsonSerializable(typeof(EnrollmentTokenResponse))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(EventResponse))]
[JsonSerializable(typeof(EventResponse[]))]
[JsonSerializable(typeof(ClientStatsResponse))]
[JsonSerializable(typeof(ClientStatsResponse[]))]
[JsonSerializable(typeof(UsageSummaryResponse))]
[JsonSerializable(typeof(ClientUsageSeriesResponse))]
[JsonSerializable(typeof(ImportResultResponse))]
[JsonSerializable(typeof(ClientShareResponse))]
[JsonSerializable(typeof(PublicShareResponse))]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(ApiError))]
[JsonSerializable(typeof(GeneratedKeyResponse))]
[JsonSerializable(typeof(UpdateNodeFailoverRequest))]
[JsonSerializable(typeof(FailoverStatusResponse))]
[JsonSerializable(typeof(UpdateFailoverRequest))]
[JsonSerializable(typeof(CreateProbeRequest))]
[JsonSerializable(typeof(ProbeResponse))]
[JsonSerializable(typeof(ProbeResponse[]))]
[JsonSerializable(typeof(ProbeAssignment))]
[JsonSerializable(typeof(ProbeReport))]
[JsonSerializable(typeof(Notification))]
[JsonSerializable(typeof(TelegramMessage))]
[JsonSerializable(typeof(ServerObfuscationProfile))]
[JsonSerializable(typeof(ClientObfuscationOverrides))]
[JsonSerializable(typeof(SignedBundle))]
[JsonSerializable(typeof(EnrollRequest))]
[JsonSerializable(typeof(EnrollResponse))]
[JsonSerializable(typeof(NodeStatusReport))]
[JsonSerializable(typeof(NodeStatusAck))]
[JsonSerializable(typeof(LegacyState))]
[JsonSerializable(typeof(LegacyBackup))]
internal sealed partial class ControlJsonContext : JsonSerializerContext;
